"use client";
import "../styles/globals.scss";

import { Fira_Code } from "next/font/google";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

const fira = Fira_Code({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={fira.className}>
        <div className="wrapper">
          <Navigation />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
